#### general settings
name: RS-UDASR-X4_trainDeg
use_tb_logger: false
model: DegSRModel
scale: 4
gpu_ids: [0]
metrics: []

#### datasets
datasets:
  train:
    name: DIV2K_Train
    mode: UnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [50, 200]

    dataroot_tgt: ../../../data_samples/RS/RS_DIV2K_train_HR.lmdb
    dataroot_src: ../../../data_samples/RS/train_RSLR.lmdb
    use_shuffle: true
    workers_per_gpu: 8  # per GPU
    imgs_per_gpu: 16
    tgt_size: 192
    src_size: 48 #48
    use_flip: true
    use_rot: true

  val:
    name: RS_LR
    mode: SingleDataset
    data_type: lmdb
#    color: RGB
    dataroot: ../../../data_samples/RS/train_RSLR.lmdb

#### network structures
networks:
  netDeg:
    which_network: DegModel
    setting:
      scale: 3
      nc_img: 3
      kernel_opt: 
        mix: false
        spatial: false
        nc: 64
        nf: 64
        nb: 16
        head_k: 1
        body_k: 1
        ksize: 21
        zero_init: true
      noise_opt: 
        mix: true
        nc: 3
        nf: 64
        nb: 16
        head_k: 3
        body_k: 3
        dim: 3
        zero_init: true
    pretrain: 
      path: ~
      strict_load: true
  netSR:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/edsr_baseline_600.pt
      strict_load: false
  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      path: ~
      strict_load: true
  netD2:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 1
    pretrain:
      path: ~
      strict_load: true
#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 5
  max_grad_norm: 50
  buffer_size: 0
  
  optim_sr: false
  optim_deg: true
  
  losses:
  
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0
    
    noise_mean:
      type: MSELoss
      weight: 100.0
    sr_pix_sr: 
      type: L1Loss
      weight: 1.0
    
    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.05
    
    sr_percep:
      type: PerceptualLoss
      layer_weights:
#        'conv1_2': 0.5  
#        'conv2_2': 0.5  
#        'conv3_4': 1  
#        'conv4_4': 1  
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      weight: !!float 0.05

  optimizers:
    netDeg:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    netSR:
      type: Adam
      lr: !!float 2e-5
#      lr: !!float 2e-7     
    netD2:
      type: Adam
#      lr: !!float 2e-7
      lr: !!float 2e-5
   
  niter: 200000
  warmup_iter: -1  # no warm up

  schedulers:
    default:
      type: MultiStepRestartLR
      milestones: [50000, 100000, 150000]
      gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e6

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
